#数据库连接信息
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/registration?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    url: jdbc:oracle:thin:@192.168.137.136:1521:helowin
    username: user1
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    #切换数据源
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /api/**
server:
  port: 8080

#整合mybatis
mybatis:
    type-aliases-package: com.bxg.registration.pojo
    mapper-locations: classpath:mybatis/mapper/*.xml
#    [开启驼峰](https://www.hellojava.com/a/93040.html)
    configuration:
      map-underscore-to-camel-case: true
#配置静态资源路径映射
#mvc:
#  static-path-pattern: /uploads/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/uploads/